title: Emil Carr-Ross
email: mail@emilcarr.scot
description: >- # ignore newlines
  Product Design Engineering Student in Glasgow, Scotland.
baseurl: ""
url: "https://emilcarr.scot"
twitter_username: EmilCarrRoss
github_username:  emil.carr

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme


minima:
  show_excerpts: true

# Theme specifics
show_downloads: false
list_posts: true
#google_analytics: #[tracking id]

paginate: false
date_format: '%d-%m-%Y'

github:
  is_project_page: false
  is_user_page: true

# SEO and social info
logo: media/alex_portrait_square.jpg
instagram:  "https://www.instagram.com/emil.carr/"
twitter:    
  username: EmilCarrRoss
  card: summary
facebook:
  publisher: "https://www.facebook.com/EmilsWheels"
social:
  links:
    - "https://www.instagram.com/emi.carr/"
    - "https://twitter.com/EmilCarrRoss"
    - "https://facebook.com/EmilsWheels"
    - "https://www.linkedin.com/in/emil-carr-ross-3943441a3/"
    - "https://purpleport.com/portfolio/emilcarrross/"
    
locale: en_GB

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
